name: Windows CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Create build directory
      run: mkdir build
    - name: Run CMake
      run: cmake -G "Visual Studio 17 2022" -DKITTY_TEST=ON ..
      working-directory: ./build
    - name: Check Visual Studio installation
      run: |
        & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -prerelease -products * -requires Microsoft.Component.MSBuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Build kitty
      run: msbuild kitty.sln /t:run_tests
      working-directory: ./build
    - name: Run tests
      run: |
        cd build
        .\test\Debug\run_tests